---
- name: Test Playbook
  hosts: localhost
  
  vars_files:
  - lookupdate.yml
  
  tasks:
  - name: Run a debug task
    debug:
      msg: "The current value of {{ lookupdate }}"  # lookupdate has the format YYYY-MM-DD
